I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 57, in script
    show coffeemug at pos(0, -50)
  File "game/script.rpy", line 57, in <module>
    show coffeemug at pos(0, -50)
NameError: name 'pos' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 57, in script
    show coffeemug at pos(0, -50)
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/ast.py", line 1117, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/ast.py", line 1076, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/ast.py", line 1076, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 57, in <module>
    show coffeemug at pos(0, -50)
NameError: name 'pos' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.4.24120703
Separation of Cultures 1.0
Tue Apr  8 20:59:48 2025
