I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 146, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "game/script.rpy", line 146, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 146, in script
    with Shake((0, 0, 0, 0), 3.0, dist=30)
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/ast.py", line 1360, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/Shreya/renpy-8.3.4-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 146, in <module>
    with Shake((0, 0, 0, 0), 3.0, dist=30)
NameError: name 'Shake' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.4.24120703
Separation of Cultures 1.0
Wed Apr  2 13:26:02 2025
